# Example: How to use the DataOps Module Quality Gate workflow
# This file shows how to call the reusable quality gate workflow from your project

name: Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

jobs:
  # Example 1: Basic usage with just the project name
  quality-gate-basic:
    uses: Aignosi/sientia/.github/workflow-templates/dataops-module-quality-gate.yml@main
    with:
      project_name: 'ingestor'  # Replace with your actual project/module name

  # Example 2: Advanced usage with custom parameters
  quality-gate-advanced:
    uses: Aignosi/sientia/.github/workflow-templates/dataops-module-quality-gate.yml@main
    with:
      project_name: 'processor'  # Your project/module name
      python_version: '3.12'     # Custom Python version
      app_owner: 'YourOrg'       # Custom GitHub App owner
      repositories: 'your-repo1,your-repo2'  # Custom repositories for app access

  # Example 3: Dynamic project name from repository name
  quality-gate-dynamic:
    uses: Aignosi/sientia/.github/workflow-templates/dataops-module-quality-gate.yml@main
    with:
      project_name: ${{ github.event.repository.name }}  # Automatically uses repository name
      python_version: '3.11'
