# Example: How to use the DataOps Module Release workflow
# This file shows how to call the reusable release workflow from your project

name: Create Release on Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  # Example 1: Basic usage with just the project name
  create-release-basic:
    if: github.event.pull_request.merged == true
    uses: Aignosi/sientia/.github/workflow-templates/dataops-module-release.yml@main
    with:
      project_name: 'ingestor'  # Replace with your actual project/module name

  # Example 2: Advanced usage with custom parameters
  create-release-advanced:
    if: github.event.pull_request.merged == true
    uses: Aignosi/Documents/projects/sientia/.github/workflow-templates/dataops-module-release.yml@main
    with:
      project_name: 'processor'        # Your project/module name
      python_version: '3.12'           # Custom Python version
      release_prefix: 'mycompany'      # Custom release prefix
      encrypt_script: 'custom_encrypt.py'  # Custom encryption script
      ignore_file: '.customignore'     # Custom ignore file
      chunk_size: '50000'              # Custom chunk size

  # Example 3: Dynamic project name from repository name
  create-release-dynamic:
    if: github.event.pull_request.merged == true
    uses: Aignosi/sientia/.github/workflow-templates/dataops-module-release.yml@main
    with:
      project_name: ${{ github.event.repository.name }}  # Automatically uses repository name
      release_prefix: 'sientia'
